ADDITION = "add"
SUBTRACTION = "sub"
MULTIPLICATION = "mul"
DIVISION = "div"
DEFAULT_NUM1_LOWER_BOUNDARY = 0
DEFAULT_NUM1_UPPER_BOUNDARY = 1000
DEFAULT_NUM2_LOWER_BOUNDARY = 0
DEFAULT_NUM2_UPPER_BOUNDARY = 1000
